### ISSUE TITLE
Announcement on mailing lists

### ISSUE THREAD

**Issue by brk00** [JuliaIO/FileIO.jl#1]
Maybe this organization should be announced on mailing lists like julia-dev or julia-users (I haven't found nothing on my searches). This would bring more people to the project, new ideas and speed things up.

**Comment by SimonDanisch** [comment]
done! 
https://groups.google.com/forum/?fromgroups=#!topic/julia-users/SL6kgIFAKUs

Best,
Simon

**Comment by brk00** [comment]
=)
