### ISSUE TITLE
How to load/save with filenames as strings?

### ISSUE THREAD

**Issue by juliohm** [JuliaIO/FileIO.jl#101]
I was following the README and wrote a simple saver:

```julia
function save{T<:AbstractFloat}(fname::File{format"GSLIB"}, A::AbstractArray{T,3})
  nx, ny, nz = size(A)

  open(fname, "w") do f
    # write header with grid dimensions
    write(f, @sprintf("%i %i %i\n1\nreal\n", nx, ny, nz))

    # flatten array and write to disk
    writedlm(f, A[:])
  end
end
```

There is no way to use it as `save("foo.gslib", ones(3,3,3))`? What is my misunderstanding here?

**Comment by timholy** [comment]
If you register `format"GSLIB"` with FileIO, then it will recognize your extension and dispatch to this method automatically.

**Comment by juliohm** [comment]
@timholy is there any way to test it before I register the package?

**Comment by SimonDanisch** [comment]
Sure, just create your package, go into your local copy of FileIO, register the file format with your package and try it out?

**Comment by juliohm** [comment]
Thanks @SimonDanisch, makes sense :+1:

**Comment by juliohm** [comment]
@SimonDanisch even after registering locally I get the following error:

>julia> save("asdf.gslib", ones(3,3,3))
ERROR: MethodError: no method matching save(::String, ::Array{Float64,3})
Closest candidates are:
  save{T<:AbstractFloat}(::FileIO.File{FileIO.DataFormat{:GSLIB}}, ::AbstractArray{T<:AbstractFloat,3}) at /home/juliohm/.julia/v0.5/GslibIO/src/GslibIO.jl:23

**Comment by timholy** [comment]
Literally follow the examples on the FileIO README. Specifically:
- don't write a version supporting `::String`
- your package should not extend `FileIO.save`
- your package should not export `save`

**Comment by juliohm** [comment]
It is working now, thanks.
