### ISSUE TITLE
Add support to writedlm

### ISSUE THREAD

**Issue by juliohm** [JuliaIO/FileIO.jl#102]
Consider the simplest saver:

```julia
function save(file::File{format"GSLIB"}, A::AbstractArray)
  open(file, "w") do f
    writedlm(f, A[:])
  end
end
```

It doesn't work because `writedlm` does not have a method for this package's' type. Do you consider adding a method for it?

**Comment by timholy** [comment]
`writedlm(stream(f), A[:])`?

**Comment by juliohm** [comment]
Thanks Tim, so it is better to just define it locally and not have it in FileIO, correct?

**Comment by juliohm** [comment]
The proposed solution is very clean already, closing this.
