### ISSUE TITLE
Support for GZ format

### ISSUE THREAD

**Issue by hpoit** [JuliaIO/FileIO.jl#118]
I would like to inform that I am working towards making Libz compliant with FileIO.

**Comment by hpoit** [comment]
Very painful process of understanding it and turning it into Julia for registry https://tools.ietf.org/html/rfc1952#page-6 (GZ format specification)

**Comment by hpoit** [comment]
Wait, what? 
```
julia> using DataFrames

julia> airline_df = readtable("/Users/randyzwitch/airline/1987.csv.gz");

julia> size(airline_df)
(1311826,29)

julia> typeof(airline_df)
DataFrame  (use methods(DataFrame) to see constructors)
```

I think I just have to see how `readtable` identifies it.

**Comment by hpoit** [comment]
```
   # (2) Path is GZip file
    elseif endswith(pathname, ".gz")
        io = gzopen(pathname, "r")
        nbytes = 2 * filesize(pathname)
```
https://github.com/JuliaStats/DataFrames.jl/blob/19821b9060a691646114c064e1bc0b8e290c8f66/src/dataframe/io.jl#L932-L935

Hi @SimonDanisch, would this pass for registry and identifying a file is a GZIP?

**Comment by hpoit** [comment]
@SimonDanisch don't worry about it, I actually tried `julia> df = readtable("/file.csv.gz")` and it takes forever. Back to bytes.

**Comment by hpoit** [comment]
Okay, I think I've got the right question now: how do I read the first two bytes of a file to check if they are equal to `0x1f` and `0x8b`. That's what I'm trying to answer. 

If the first two bytes are equal to those, then the file is a GZIP.

**Comment by hpoit** [comment]
Hi @SimonDanisch, can I PR this? Is it correct? 
`add_format(format"GZIP", [0x1f, 0x8b], ".gz", [:Libz])`

**Comment by hpoit** [comment]
Hi @SimonDanisch, here goes the test, not sure I passed it
```
julia> Pkg.test("FileIO")
INFO: Testing FileIO
these tests will print warnings: 
Library "NotInstalled" is not installed but is recommended as a library to load format: ".not_installed"
Should we install "NotInstalled" for you? (y/n):
Library "NotInstalled" is not installed but is recommended as a library to load format: ".not_installed"
Should we install "NotInstalled" for you? (y/n):
invalid is not a valid choice. Try typing y or n
Should we install "NotInstalled" for you? (y/n):
this test will print warnings: 
Errors encountered while loading "test.multierr".
All errors:
   ErrorException("1")
   ErrorException("2")
Fatal error:
Test Summary: | Pass  Total
  FileIO      |  108    108
INFO: FileIO tests passed

julia> 
```
Should I just PR for you to see what I've done?

**Comment by timholy** [comment]
A PR would be great!
