### ISSUE TITLE
Libz compliance with FileIO for GZ format

### ISSUE THREAD

**Issue by hpoit** [JuliaIO/FileIO.jl#120]
Hi @SimonDanisch and @timholy, 

In general terms, what does it mean to make Libz compliant with FileIO? That's my next goal. 
Libz can read from a GZ and write to another GZ. FileIO just detects the GZ format and dispatches it to Libz, which I believe I've already done with `add_format(format"GZIP", [0x1f, 0x8b], ".gz", [:Libz])`. 

Is there any more compliance to be done between the two? 

Cheers, HP

**Comment by SimonDanisch** [comment]
Yes, that looks correct!
Please refer to the documentation for implementing the loading scheme:
https://github.com/JuliaIO/FileIO.jl#implementing-loaderssavers
Or have a look at a library that already implements this, e.g:

https://github.com/JuliaIO/NRRD.jl/blob/master/src/NRRD.jl#L199
https://github.com/JuliaIO/MeshIO.jl/blob/master/src/MeshIO.jl#L20

Best,
Simon

**Comment by hpoit** [comment]
Hi @SimonDanisch, you highlighted line 199 of NRRD, is it not 206 in the case of a stream?

**Comment by hpoit** [comment]
Actually this whole bit https://github.com/JuliaIO/NRRD.jl/blob/master/src/NRRD.jl#L206-L302?

**Comment by timholy** [comment]
I don't think there's anything more to do here but wait for a PR.
