### ISSUE TITLE
How does this integrate with the general mime writing scheme in base?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/FileIO.jl#122]
Say I have a custom plot type ``MyPlot``. Lets also assume I already have defined a ``show`` method for the ``image/png`` mime type:
````julia
function Base.show(io::IO, m::MIME"image/png", v::MyPlot)
````
I would have assumed that ``save("filename.png", p)`` where ``p`` is a ``MyPlot`` would just work? Or how could that be integrated?

I guess in general, if a type has a ``show`` method for a given mime type, and that mime type corresponds directly to a given file extension, it should be straightforward to just save things to a file with the ``save`` function?

**Comment by timholy** [comment]
Short answer, I don't think there is any integration now, and I'm not particularly fresh on my how-julia-handles-MIME at the moment (come to think of it, I haven't hacked on this package recently, either). If you want to add this, I think it would be reasonable to add a runtime check, I'd guess to [this function](https://github.com/JuliaIO/FileIO.jl/blob/4aadcda03c4847999fd7d3014ae24eb14fed43c9/src/loadsave.jl#L94-L110).

**Comment by davidanthoff** [comment]
Hm, it seems to me that what we would want here is another registered package that provides save functionality for say png, svg etc. files. That provider would check whether the ``data`` argument to the ``save`` function returns ``true`` for say ``mimewritable(MIME"image/png", data)``, and if so, just directly writes whatever the ``show`` method for that type returns if you ask for the png representation to disc. If the call to ``mimewriteable`` returns false, that ``save`` function would throw an error, and then [this](https://github.com/JuliaIO/FileIO.jl/blob/4aadcda03c4847999fd7d3014ae24eb14fed43c9/src/loadsave.jl#L94-L110) function would try the next registered package for that image type.

@SimonDanisch Does that sound right? I guess one question is whether this should actually be in a separate package, or whether we could just have that functionality in FileIO itself?
