### ISSUE TITLE
Find magic byte for .sav file

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/FileIO.jl#129]
@evanmiller Sorry to bother you here, but you can probably answer this question in a heartbeat: is there a magic byte sequence for SPSS .sav files? I integrated ReadStat.jl with the generic ``load`` function here, and we were wondering whether there is such a magic byte sequence for .sav files. Thanks!

**Comment by evanmiller** [comment]
`$FL2` and `$FL3` I think

**Comment by davidanthoff** [comment]
Great, thanks! ``$FL2``seems to be the right one. From what I can tell ``$FL3`` is for a new format ``.zsav``. Does ReadStat support that as well? If so, I would add that as a separate format here.

I tried to find a magic bytes for ``*.dta`` files (also by looking at the ReadStat code), but didn't come up with anything. @evanmiller, any pointer would be greatly appreciated!

**Comment by evanmiller** [comment]
ReadStat does not support .zsav.

Newer DTA files begin with `<stata_dta>`. For older files it's more complicated.

**Comment by davidanthoff** [comment]
@evanmiller: Ah, thanks, that is really helpful information!

@SimonDanisch I'd say we skip magic bytes for ``*.dta`` files in that case as we would like to open old files as well. Plus, there doesn't really seem to be a extension naming conflict for ``*.dta`` files so far.
