### ISSUE TITLE
save code path should never check magic bytes

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/FileIO.jl#132]
If one calls ``save("filename.ext", data)`` and the file ``filename.ext`` exists already, FileIO will open the existing file and check the magic bytes in there to determine which package it should use for saving ``data``. That makes no sense, the ``save`` code path should only use the file extension to pick a package for saving and ignore any existing file.

**Comment by SimonDanisch** [comment]
good point... We had some discussion about this, not sure why we didn't change it.
@timholy was there any use case for this?

**Comment by timholy** [comment]
Yeah, I can't think of a reason we'd want the current behavior. Would be worth changing and then running the tests; if there is a good reason, we should have encapsulated it in the tests.

**Comment by damiendr** [comment]
One consequence of this issue is that if the target file gets corrupted, it can no longer be overwritten:

```julia
>>> write("target.png", "oops")
>>> save("target.png", img)
ERROR: LoadError: FileIO.File{FileIO.DataFormat{:UNKNOWN}}("target.png")
couldn't be recognized by FileIO.
```

**Comment by damiendr** [comment]
I have a patch ready that makes `save(::AbstractString, data...)` a special case. I can do a PR for that, but maybe it's worth looking a bit more into whether the query and save/load methods need re-organising.

**Comment by timholy** [comment]
I think this has long been fixed. If not, #295 should have fixed it.
