### ISSUE TITLE
Resolve between binary and ASCII formats

### ISSUE THREAD

**Issue by sjkelly** [JuliaIO/FileIO.jl#14]
In Meshes there are often binary and ASCII formats for each file type. There doesn't seem to be a way to resolve which one you would like easily. For example `file"foo.ply` creates a `File{:ply}("foo.ply")`, but the only dispatchable signatures are `File{:binary_ply}`, so I cannot use the `m_str` form.

What should be the behavior here?

**Comment by SimonDanisch** [comment]
I wrote a prototype to solve this and opened an issue to get some feedback in #13

**Comment by timholy** [comment]
Closed by #15, see https://github.com/JuliaIO/FileIO.jl/blob/eb9a416bbc25d8727b652857d2d9e8fc243894bc/src/registry.jl#L7-L12
