### ISSUE TITLE
query metadata feature?

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/FileIO.jl#173]
`query` returns the file type (e.g. tiff), but i frequently need to know the size (e.g. 1024x768 pixels) without actually loading the whole image.  does FileIO provide an interface for this?

pretty straightforward to implement this for ImageMagick as follows:

```
function get_image_dimensions(file)
    wand = MagickWand()
    readimage(wand, file)
    xy=size(wand)
    z=getnumberimages(wand)
    z==1 ? xy : (xy...,z)
end
```

happy to submit a PR, just tell me how to do it.  thanks.

**Comment by bjarthur** [comment]
i propose we had to FileIO a `metadata` function, to add to `load` and `save`, which for files containing images returns a sub-package (e.g. ImageMagick.jl) defined type that contains the width, height, depth, eltype, etc.  `METADATA` would be defined to add to the existing `LOAD` and `SAVE`.  similarly, `add_metadata` would complement `add_{loader,saver}`.  happy to work on a PR but would like to hear what people think first.

**Comment by timholy** [comment]
Does one need a separate `add_metadata` or is that implicit with `add_loader`? Is there a case where the loading package *wouldn't* be the one to return the metadata?
