### ISSUE TITLE
detect functions never called for files < 35 bytes

### ISSUE THREAD

**Issue by ssfrr** [JuliaIO/FileIO.jl#176]
The logic [here](https://github.com/JuliaIO/FileIO.jl/blob/50c4ef3438a7165d8a0789808530cb734bc3cadb/src/query.jl#L409-L412) will return the query with `format"UNKNOWN"` if it hits EOF while going through the magic bytes list, but some of the magic byte strings are quite long (35 bytes). So if you have a short file that relies on a detection function (like .wav), that detection file will never get called.

**Comment by timholy** [comment]
I'm pretty sure this is fixed now, but if not a MWE would be great.
