### ISSUE TITLE
Corrupted magicbytes

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/FileIO.jl#19]
Right now this happens:

``` julia
f = "test.nrrd" #empty file
load(f) 
#ERROR: No load function defined for format FileIO.DataFormat{:UNKNOWN} with filename test.nrrd
save(f) 
#ERROR: No save function defined for format FileIO.DataFormat{:UNKNOWN} with filename test.nrrd
```

For load we should probably fall back to the file ending or have something like `DataFormat{:NRRD_CORRUPTED}`.
For `save` it should probably just work and overwrite it. Or do we want to warn the user and make them use e.g. `save!` for overwriting?!

**Comment by timholy** [comment]
It already does: http://docs.julialang.org/en/release-0.3/manual/packages/#package-development. But nothing will happen if the format hasn't been registered.

**Comment by SimonDanisch** [comment]
But not if there is an empty file with the name, as `isfile` becomes `true`...

**Comment by timholy** [comment]
Oh, I see. Sure, we should fall back on the extension more readily, then.

**Comment by timholy** [comment]
I think this is fixed.
