### ISSUE TITLE
ImageMagick

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/FileIO.jl#20]
I tried to find as much extensions and magic bytes as possible for ImageMagick, but am still not there.
As I dislike the idea to just let ImageMagick load everything without extension, I would suggest I add all the formats I could determine and the rest will get added on demand.
Like this, the work will be spread over a bigger amount of time, but we will still be able to read the most important formats.

**Comment by timholy** [comment]
Oh, shoot, I should have explained my current thinking. I think it will be easiest if we define
```
function FileIO.load(file::File{format"ImageMagick"}, args...)
```
That translates into "you figure it out, ImageMagick"! Within Images, `imread` will `query` and then for `format"UNKNOWN"` it will translate it into `format"ImageMagick"`.

Sound reasonable? We only need to define magic bytes for formats that we want to define our own readers for, and which should take precedence over ImageMagick.

This is basically my current incarnation of https://github.com/JuliaIO/FileIO.jl/pull/16; I like this better than `load_`.

**Comment by timholy** [comment]
Though I should add that it's not a bad thing to register any magics you've dug up. I mostly mean we can have a fallback.

**Comment by SimonDanisch** [comment]
Yes, I think its nicer to have this explicit. The conflict arises when we
have multiple catch all libraries (which we actually already have with
VideoIO). We can only have one catch-all afterall. Also its nice to have
this collection, as we can already see what the challenges are if we move
forward with FileIO.

**Comment by timholy** [comment]
Can this be closed?
