### ISSUE TITLE
Precompilation: registry objects not shared between packages (and REPL) on 0.7

### ISSUE THREAD

**Issue by damiendr** [JuliaIO/FileIO.jl#200]
I'm working on a parser and would like to make it work with FileIO on Julia 0.7.

It seems that the package that contains my parser and the REPL see different instances of the FileIO registry objects, so that the package can't make itself available through FileIO.

Running Julia with `--compiled-modules=no` seems to fix the issue, so it looks like a precompilation bug.

```julia
julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

julia> using FileIO

julia> length(FileIO.sym2info)
66

julia> Int(objectid(FileIO.sym2info))
2524267961438205744

julia> using MyPackage
[ Info: Recompiling stale cache file <...> ]
[MyPackage] objectid(FileIO.sym2info): 5803759617398206105
[MyPackage] Registering file format with add_format(format"ROSBAG", "#ROSBAG", ".bag")
[MyPackage] FileIO.sym2info: 67 formats declared

julia> length(FileIO.sym2info)
66
```

**Comment by damiendr** [comment]
And this is in my Manifest.toml (same in the REPL environment and my package):

```
[[FileIO]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "b80161b7e679a1241f9441ebfa60b62d4239cf99"
repo-rev = "master"
repo-url = "https://github.com/JuliaIO/FileIO.jl.git"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.0.1+"
```

**Comment by damiendr** [comment]
Suggested fix: use
```julia
VERSION > v"0.7.0-beta2.199" && __precompile__(false)
```
instead in `FileIO.jl`, or define an `__init__()` method.

**Comment by SimonDanisch** [comment]
>add_format() must do so inside its __init__() method.

That is correct - But you should actually register with a PR to FileIO, and directly put your package in the FileIO registry.

Putting it into your package in the `__init__()` is kind of wrong, since FileIO is supposed to know about your loader without it being loaded!

**Comment by damiendr** [comment]
Mm, yes, that makes sense. But I can't make that PR until I know that the package works fine. I guess the best practice would be to have the package register itself when loaded in the meanwhile?

I think what remains from the issue after all this is
- it would be helpful if the FileIO doc reminded users of the precompile/`__init__()` issue
- the recent PR https://github.com/JuliaIO/FileIO.jl/commit/8600b3ced9a44c12fafa7963cf80e7c2c7b60be8 does not achieve its stated goal, since precompilation must now be explicitely disabled with `__precompile__(false)` rather than conditionally enabled.

**Comment by SimonDanisch** [comment]
>register itself when loaded in the meanwhile?

Maybe for a quick check, but otherwise I'd just locally change it in FileIO and when you're ready push the change as a PR
