### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by musm** [JuliaIO/FileIO.jl#216]
cf. https://github.com/JuliaIO/FileIO.jl/issues/213#issuecomment-439657407

**Comment by vtjnash** [comment]
> Better though to capture the each backtrace along with the exception using catch_backtrace() and communicate the set of those errors to the user somehow. There's a mixture of logging and throwing already in the package...

This would be great. It's currently a unpleasant to debug errors since this package is discarding the backtrace stack in it's effort to be more user-friendly.

**Comment by timholy** [comment]
This seems stale because there are no `rethrow`s anywhere in the package.

**Comment by vtjnash** [comment]
It seems to still lack the backtrace handling described in the original comment at https://github.com/JuliaIO/FileIO.jl/blob/1d9d38270fa49fbeeab5fda9ce343371fc68c296/src/loadsave.jl#L218

**Comment by timholy** [comment]
Oh, good point. I'll add that.
