### ISSUE TITLE
Numpy files

### ISSUE THREAD

**Issue by mtikekar** [JuliaIO/FileIO.jl#217]
I noticed that the loaders for npy and npz files are commented out in registry.jl. I understand the issue with npz (#32), but is there any reason the npy files should not work? We would only need to add the appropriate load/save functions to https://github.com/fhs/NPZ.jl

**Comment by timholy** [comment]
Dunno. Care to try implementing it and submitting a PR?

**Comment by ViralBShah** [comment]
Looks like d3d941e1a494e57938b4ee3579fe50a72cd0c995 did it.
