### ISSUE TITLE
Support URLs and FilePaths

### ISSUE THREAD

**Issue by rofinn** [JuliaIO/FileIO.jl#219]
It'd be nice if the API could be loosened to include [`URI`](https://github.com/JuliaWeb/URIParser.jl/blob/master/src/parser.jl#L13) and [`AbstractPath`](https://github.com/rofinn/FilePathsBase.jl/blob/master/src/FilePathsBase.jl#L84) types.

Related issues: #89, https://github.com/rofinn/FilePaths.jl/issues/34, https://github.com/rofinn/FilePaths.jl/pull/22#issuecomment-370620375

**Comment by timholy** [comment]
Added in #302
