### ISSUE TITLE
save changes view

### ISSUE THREAD

**Issue by edljk** [JuliaIO/FileIO.jl#220]
It seems that a rotation in `Makie` is not recorded in a scene which produces a difficulty when saving a specific view chosen with the mouse (for instance). How to save a specific view of  a scene: a call like  

 ```julia
FileIO.save(myfile, scene)
``` 
reinitialize the view of a scene..

**Comment by SimonDanisch** [comment]
oh, that may be, because i call center in display -.- i'll need to refactor that, but meanwhile, you can do `scene.center = false` before you save!

**Comment by edljk** [comment]
Problem solved with  `scene.center = false`. Thanks!
