### ISSUE TITLE
Support for gz-compressed RData files

### ISSUE THREAD

**Issue by alyst** [JuliaIO/FileIO.jl#225]
In JuliaData/RData.jl#57 we have ran into problems with gzip-compressed R Data file with non-registered extension (`.Rda`). Since none of FileIO-registered extensions were matched, `load()` was trying to detect the format by looking into magic bytes. Naturally, the file was detected as gzip archive.

Would it be possible to fix the way RData files are registered in FileIO, so that gzipped files with non-standard extension are correctly recognized as RData? Is there a generic way to specify that the given file format could exist in compressed and uncompressed forms? (It would be useful not only for RData, but e.g. for compressed XML, SVG)

**Comment by SimonDanisch** [comment]
previous discussion: https://github.com/JuliaIO/FileIO.jl/issues/32
