### ISSUE TITLE
add support for JDF.jl

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaIO/FileIO.jl#235]
see https://github.com/xiaodaigh/JDF.jl

**Comment by timholy** [comment]
If anything is unclear about the documentation on how to add support for a new format (https://github.com/JuliaIO/FileIO.jl), let us know.

**Comment by timholy** [comment]
If that package is brand new, it also might make sense to get a bit of community buy-in before registering it here.

**Comment by xiaodaigh** [comment]
Makes sense. Just like a place so I am less  likely to forget when it's stable

**Comment by timholy** [comment]
We'll wait for a PR.
