### ISSUE TITLE
detect_bedgraph function leads to extreme delays as loader attempts to scan entire file

### ISSUE THREAD

**Issue by tlnagy** [JuliaIO/FileIO.jl#241]
As I pointed out in https://github.com/JuliaIO/FileIO.jl/issues/189#issuecomment-557757946, loading OMETIFF files using `FileIO` is 3x slower than directly calling [`OMETIFF.load`](https://github.com/tlnagy/OMETIFF.jl/blob/7a65cf15d143f79cc5b0be2a15d31cf8bbc6b873/src/loader.jl#L7). Profiling the code led me to the culprit. It appears that the bedgraph parser attempts to read the _entire_ file to find the magic bytes:

https://github.com/JuliaIO/FileIO.jl/blob/f337595565a99c105a0434af0673eebdd17915c3/src/registry.jl#L168-L169

Which, with large files like my OME-TIFFs, takes a lot of time. Commenting out the bedgraph parser gets rid of the delay. This doesn't appear to effect other parsers because they are checked earlier in the loader cycle (i.e. before the bedgraph parser runs). 

I can think of a couple solutions off the top of my head:

- [ ] Move the OMETIFF header check earlier
- [ ] Have a timeout for checking the header for all functions
- [ ] Cap how far `detect_bedgraph`can search

@timholy, roping in @CiaranOMara since they are the author of #158 

Thoughts?

**Comment by timholy** [comment]
Thanks for debugging this. I'll wait for @CiaranOMara to comment about the feasibility of speeding this up (do all [such files](https://genome.ucsc.edu/FAQ/FAQformat.html) begin with "browser position"?), otherwise I think we'd need to make the bedgraph magic bytes detector run only if the file extension matches. I think even putting it last in the list is not acceptable, since users would have the delay just to find out whether it matches.

**Comment by CiaranOMara** [comment]
My apologies for that oversite.

It is possible to speed up bedGraph detection. @timholy, as you point out, there are other recognisable strings in the header of such files. The presence of these strings can be used to constrain/cap the scan.

I'll open up a PR with a suggested fix.

**Comment by tlnagy** [comment]
I can confirm that #242 is ~3x faster versus master

#### #242

```julia
julia> @benchmark load("/Users/tamasnagy/Downloads/full_chip_1_MMStack.ome.tif")
BenchmarkTools.Trial:
  memory estimate:  580.20 MiB
  allocs estimate:  47992
  --------------
  minimum time:     1.745 s (0.87% GC)
  median time:      1.773 s (4.75% GC)
  mean time:        1.819 s (4.40% GC)
  maximum time:     1.939 s (7.25% GC)
  --------------
  samples:          3
  evals/sample:     1
```

#### master

```julia
julia> @benchmark load("/Users/tamasnagy/Downloads/full_chip_1_MMStack.ome.tif")
BenchmarkTools.Trial:
  memory estimate:  580.20 MiB
  allocs estimate:  47992
  --------------
  minimum time:     4.502 s (0.33% GC)
  median time:      4.544 s (1.10% GC)
  mean time:        4.544 s (1.10% GC)
  maximum time:     4.586 s (1.87% GC)
  --------------
  samples:          2
  evals/sample:     1
```

Would be great to have it merged ASAP
