### ISSUE TITLE
segfault in travis CI

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/FileIO.jl#245]
Segfault is observed for Julia 1.0 and FileIO v1.2.0 on travis-CI when loading images with ImageMagick backend, I'm not sure how broadly this affects other repositories, but if that happens, rollback to FileIO v1.1.0 works (ImageMagick version is not changed).

Local usage and julia v1.3 seem not affected by this, actually, I'm not sure that the root cause is in this package, but I'd like to open this issue for a while in case others meet the same problem.

More details can be found in https://github.com/JuliaImages/juliaimages.github.io/pull/98

**Comment by timholy** [comment]
Probably worked around in #249
