### ISSUE TITLE
`loadstreaming` and `savestreaming` implementations?

### ISSUE THREAD

**Issue by goretkin** [JuliaIO/FileIO.jl#252]
I wasn't able to find any package in the JuliaIO org that implements the functions `loadstreaming` and `savestreaming`. Are there any?

**Comment by johnnychen94** [comment]
Do you mean `read` and `write` (from `Base`)?

**Comment by goretkin** [comment]
I found one here:
https://github.com/JuliaAudio/LibSndFile.jl/blob/e431d21ccbd50029c3f2feeac602afd528a18e75/src/loadsave.jl

but it's the only one I found beside the example in the README.

**Comment by Luapulu** [comment]
I have an implementation in [MaGe.jl](https://github.com/Luapulu/MaGe.jl), but it's not even registered, nor is it in the FileIO registry. But it's there if you want a reference.

**Comment by goretkin** [comment]
Thanks!

https://github.com/Luapulu/MaGe.jl/blob/75ec88413b8a994d4230ddb985f0838c3b556e32/src/root-hit-files.jl#L87-L98

I opened this issue because I was trying to get a handle on when to use this API, and I think I was surprised not to find it used more. e.g. `loadstreaming` does not appear here: https://github.com/JuliaIO/VideoIO.jl/blob/7e05dc3451a38885ff6e762da7899783aa5aa6ee/docs/src/reading.md , though the file is read in a streaming manner.

**Comment by Luapulu** [comment]
That's odd!

I should note that because my package isn't actually in the file format registry, the implementation is slightly different to what it will be when registered. (I don't dispatch on the format for example)

**Comment by timholy** [comment]
I'm not sure there's a TODO here? There's also an implementation in the test suite.
