### ISSUE TITLE
Loading images with ImageMagick backend within a package

### ISSUE THREAD

**Issue by VPetukhov** [JuliaIO/FileIO.jl#277]
I have a package ([Baysor](https://github.com/kharchenkolab/Baysor)), which has both Images and ImageMagick in its [dependencies](https://github.com/kharchenkolab/Baysor/blob/develop/Project.toml#L22). And I have a [function](https://github.com/kharchenkolab/Baysor/blob/master/src/data_processing/prior_segmentation.jl#L23) that loads images. So, when one installs the package, ImageMagick is technically installed, but it's not in the global julia environment, so one needs to activate Baysor before using it (which is fair). However, when one tries to call the Baysor function, which loads images, it results in `ArgumentError("Package ImageMagick not found in current path:\n- Run import Pkg; Pkg.add(\"ImageMagick\") to install the ImageMagick package.\n")` (see https://github.com/kharchenkolab/Baysor/issues/6). Which means that anyone who wants to use Baysor, needs to install ImageMagick manually, and it kills the whole point of automated management of package dependencies. I suppose that calling `ImageMagick.load` instead of `Images.load` would work there, but ImageMagick [readme](https://github.com/JuliaIO/ImageMagick.jl#usage) explicitly says that "You should **not** generally say `using ImageMagick`". Would it be possible for FileIO to search ImageMagick within the environment of the current project, or should the ImageMagick suggestion simply be ignored in my case?

**Comment by johnnychen94** [comment]
FileIO is only a convenient frontend and it does not handle package dependencies; what it does is to find and adapt existing backends. So yeah, the user needs to choose to install whatever backends they like.

There is a decision in Images to add ImageMagick as a dependency of Images so that this issue "get fixed" for normal users.
https://github.com/JuliaImages/Images.jl/issues/824#issuecomment-683412325 However, for compatibility maintenance consideration, we have to wait for Julia 1.6 LTS release.

**Comment by VPetukhov** [comment]
Thanks for the answer!

> what it does is to find and adapt existing backends

Yep, I actually meant that it could be nice to search backends within the environment of the package that calls `Images.load`. Though I understand that it would get complicated for nested calls. But anyway, if you say it will be fixed with Julia 1.6, there is no reason to search for alternative solutions :)

**Comment by johnnychen94** [comment]
BTW, in the very early version of FileIO, it gives you an interactive prompt to install ImageMagick when it's not available. See also https://github.com/JuliaIO/FileIO.jl/pull/226#issuecomment-492157300 and https://github.com/JuliaLang/julia/issues/13482#issuecomment-148840438

**Comment by SimonDanisch** [comment]
I think it's totally fine to have `import ImageMagick` inside `Baysor`!
The only thing you're loosing is, that the user can't as easily chose which image IO library to use.
But seems like that isn't the goal here ;)
