### ISSUE TITLE
Ignore missing packages required by loaders

### ISSUE THREAD

**Issue by jdonnerstag** [JuliaIO/FileIO.jl#279]
Hi, 

FileIO complains that I need to install the ImageMagick package. But I have no intention to load/save ImageMagick files, and hence no intention/interest to add that package.

How can I unregister all loaders that require packages which I do not have installed?

thanks a lot

**Comment by SimonDanisch** [comment]
I'm not sure if I understand your question, but the direct answer seems to be: don't use FileIO to load files (images) that are only loadable by ImageMagick?

If you're running into ImageMagick shadowing e.g. loading jpegs/pngs with `ImageIO` (which is currently the only alternative) or PNGFiles, then you can simply install those and load them, and FileIO will not try to use ImageMagick.

**Comment by ianshmean** [comment]
Just a detail.. ImageIO is still png's only

**Comment by jdonnerstag** [comment]
Sorry, if I wasn't clear. Our application has nothing to do images, but FileIO seems to force me to add the Julia ImageMagick package. How can I avoid that have to load this (and possible other) Julia packages, which are not needed in our use case.

**Comment by SimonDanisch** [comment]
That shouldn't happen. FileIO only ever complains about packages missing, once you try to load a file that can only be loaded by that package.
Check (post) the stack trace, to see where it complains.

**Comment by jdonnerstag** [comment]
thanks for your help. I readdir() on the wrong directory and got julia (test) source code file "*.jl" instead. Now with correct folder and files, it is picking up the correct loader and not throwing an error anymore.
