### ISSUE TITLE
Add github topic (eg. hashtag) to enhance discoverability in github, juliahub

### ISSUE THREAD

**Issue by o314** [JuliaIO/FileIO.jl#281]
It could be a good fit to add topics (eg. hashtag) in github such as to enhance discoverability in github, juliahub

Those ones seem pretty commons :

- `file`
- `file-formats` # file-format has a better rank; but homogeneity brings guessability
- `mime`
- `mime-types` # better rank than mime-type, mimetype, mimetypes @ github topics
- `magic-numbers` # better rank than magic-number, magicnumber, magicnumbers @ github topics

*PS: Here is the link to the doc if needed https://docs.github.com/github/administering-a-repository/classifying-your-repository-with-topics*

**Comment by timholy** [comment]
Done, thanks for the suggestion, the list of topics, and the background link.

**Comment by o314** [comment]
Welcome. Thanks you also for your quick intervention
