### ISSUE TITLE
Unexpected magic behaviour

### ISSUE THREAD

**Issue by PaulDebus** [JuliaIO/FileIO.jl#292]
Hey,

I am implementing a reader/writer for the Bundler format for SfM results. In my local clone, I add it with
```julia
add_format(format"OUT", "# Bundle file v0.3", ".out", [:BundlerIO])
```
Surprisingly, it does not work as I expected, as the reading position is on the newline `\n` at the end of the magic line. An example to test this can be found [here](https://github.com/snavely/bundler_sfm/blob/master/examples/kermit/results.example/bundle.out).

I implemented a manual fix, so my current code looks like this:

```julia
function load(f::File{format"OUT"}; colors=true, keypoints=true, F=Float64)
    open(f) do s
        skipmagic(s)  # skip over the magic bytes
        load(s, colors=colors, keypoints=keypoints, F=F)
    end
end

function load(ss::Stream{format"OUT"}; colors=true, keypoints=true, F=Float64)
    s = stream(ss)
    read(s,1) 
    ....
end
```

Is this expected behavior? If so, feel free to close this issue and I will leave the `read` line in.

**Comment by timholy** [comment]
I'm a bit confused about what you're asking. Does FileIO automatically write the newline for you, given your `add_format` declaration? Or are you complaining that it *doesn't* write a newline. (It's been a while so I forget if it does this.) The style you wrote your `load` in is exactly the recommended style, so I am not sure I understand the nature of the problem that concerns you.

**Comment by PaulDebus** [comment]
Thanks for the answer. I was not complaining, just expressing something unexpected that might surprise others. I am sorry if it came over as a complaint. It just took me some time to figure out why my loader was not working at all because the first thing it read was an empty line that is not admissible in the format and not there in my file. 

FileIO does *not* write the newline, which surprised me as I expected to be at the beginning of the first content line after the `skipmagic`. I did not see the other loaders I looked at dealing explicitly with this. 

Now after thinking a little more about this, it totally makes sense, that FileIO is not writing a newline, as it is absolutely not the case for every format, that a newline comes after the magic. Also, as the magic does not contain the final `\n`, it would be even more surprising if it was skipped. Maybe a remark in the docs would have helped me here. 

To close this, what would be the recommended style, adding a `\n` at the end of the magic or skipping one character while loading the file? Either way, thanks for your support!

**Comment by timholy** [comment]
> I was not complaining, just expressing something unexpected that might surprise others

Even though I used the word "complaining" I didn't mean it in a negative way...I just didn't understand what specific point you were making, and if something is behaving badly you would have every right to complain. I just wanted to understand the locus of the problem, and I didn't.

I would say that including the newline as part of the magic makes the most sense.
