### ISSUE TITLE
Suggestion: don't use file suffixes to determine initial type

### ISSUE THREAD

**Issue by sbromberger** [JuliaIO/FileIO.jl#3]
It might be better to use [magic numbers](http://en.wikipedia.org/wiki/List_of_file_signatures) to detect what kind of file you're trying to access. This may cause problems with internally-formatted text files (like CSV), but at that point perhaps the file suffix makes sense.

**Comment by SimonDanisch** [comment]
Why not both!
The list seems short, so it should be relatively easy to integrate.
I really like the idea of having the type information in the parameter of the file. So to keep things homogeneous we could apply a pattern like this:
```Julia
const MAGIC_NUMBERS = Dict(
[BE, BA, FE, CA] => :dba,
[00, 00, 00, nn, 66, 74, 79, 70,
33, 67, 70, 35] => :mp4,
...
)

function File(path)
	path = abspath(path)
	magicnumber = readmagicnumber(path)
	file_ending = get(MAGIC_NUMBERS, magicnumber) do
		_, ending = splitext(path)
		symbol(ending[2:end])
	end
       #todo check if magic number and ending agree...
	File{file_ending}(path)
end
```
Like this, we're still be able to overload read for all the different file formats.

**Comment by sbromberger** [comment]
That's a more elegant approach. +1.

**Comment by sebastiang** [comment]
Consider reading a file extension, a mime type (if you have it) and the first, say, 4k, of a file, and handing it to a series of predicate functions. The one with the best match is chosen. This allows you to extend the system by registering more predicates; 3rd parties could even do so. It's often quite easy to assign a confidence that a file is of a certain form by looking at the first few kb of data. And if you're going to hit the disk to look at the magic number anyway, the OS has already retrieved at least that much

**Comment by timholy** [comment]
All of this is implemented.
