### ISSUE TITLE
Should we treat compressed files differently?

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/FileIO.jl#32]
As compressed files come as an e.g. zip, which is its own data format, but contain some other file, it might make sense to give them special treatment.
I tried to integrate [NPZ](https://github.com/fhs/NPZ.jl), which is basically a compressed NPY file, so it first has the magic bytes of a zip file, but you wouldn't really like to get a zip filereader returned but rather the uncompressed python array.
So should we deeply integrate all the compression libraries, uncompress files first and then do the "real" loading?
CC: @fhs, @hustf

Best,
Simon

**Comment by ssfrr** [comment]
I don't think that transparently opening .zip files is necessary. I mean, it makes sense for a Zip package to be registered as a file handler with FileIO, but I'd think returning a filereader is OK, and then you could use to navigate the contained files, and then hand one of those contained file objects to `load` and it would look at the filename and or magic bytes as with a normal file. Then I guess it would be possible for someone to add a `.npz` handler that would handle that chaining automatically, but it would be just thin sugar.

**Comment by SimonDanisch** [comment]
How to enable adding the NPZ handler is the problem, since `.zip` and `.npz` share the same magic bytes, which is currently not allowed. So just treating compressed files differently would circumvent this problem.

**Comment by SimonDanisch** [comment]
And what if the archieve just contains one file? Are the use cases where it would make sense to not unzip it even in that case?

**Comment by ssfrr** [comment]
I think the only argument is that in general you don't know ahead of time how many files are inside, so  code calling `load("somefile.zip")` shouldn't get a different result type if there was only one file inside. I could see the `.npz` wrapper assuming there's only one file though.

re: distinguishing `.npz` and `.zip` files - I haven't yet really grokked how the format lookup happens when you `load` or `save` a file, but would it be reasonable to match on *both* magic bytes and  extension for cases like this?

**Comment by SimonDanisch** [comment]
Sure, that'd be the way to go then.. It's just not implemented yet.
Before I or someone else implements it, I just want to make sure that it's really what we want.
I actually want to implement opening folders at some point anyway: `load(paths::Vector{String}) --> Vector{Files}`. So that would fit nicely with zip files. What doesn't fit nicely is, that you might want to have more control, e.g. only unzipping a few items in a folder.

**Comment by timholy** [comment]
It's now possible to call `detect_compressed` from your own detector function.
