### ISSUE TITLE
House AVSfldIO.jl under JulioIO ?

### ISSUE THREAD

**Issue by JeffFessler** [JuliaIO/FileIO.jl#335]
As mentioned in #333, it would make sense (to me anyway) to house the package
https://github.com/JeffFessler/AVSfldIO.jl
under JuliaIO, now that it is part of FileIO 1.9.0.
I'd like to retaining maintainer access to AVSfldIO (probably goes without saying).

@johnnychen94 queried @IanButterworth about this question over there but it may have gotten lost in the noise of that PR so I thought I'd make this a separate issue where the JulioIO group can resolve it up or down.

**Comment by JeffFessler** [comment]
It's been almost 2 months since I made the request to relocate AVSfldIO.jl to JulioIO and I've heard nothing one way or the other, so I guess my request is not reaching the right people.  So now I am going to try again by pinging the first 6 people under JuliaIO and hoping that one of them can reply.
@Agent-Hellboy @andreasnoack @ararslan @asinghvi17 @bicycle1885 @giordano
I'm sorry if this is spam but I don't know any better way.
Package discovery can be a challenge in Julia and grouping things in organizations can really help so I hope you understand that my intention is to help the cause here.

**Comment by IanButterworth** [comment]
Sorry @JeffFessler I missed your first message. 

When not getting a response, feel free to just ping the issue with the same people. Some say every 2 weeks is fair. 

Moving it into JuliaIO sounds good to me. I might have time later today to do that

**Comment by IanButterworth** [comment]
By the way, the easiest way is to give me admin rights on the repo and I can transfer it over

**Comment by giordano** [comment]
You can't give someone else admin rights to a repo under a user's account, you can only transfer the repository to someone else

**Comment by JeffFessler** [comment]
Good to know about the 2 week rule of thumb :)
@IanButterworth I tried to transfer rep ownership directly to JuliaIO but github wouldn't allow that because I don't have permissions there.  So then I put in a request to transfer ownership to you.  Hopefully then you can in turn transfer it to JuliaIO.  Thanks!

**Comment by IanButterworth** [comment]
Should be done now

**Comment by JeffFessler** [comment]
Thanks!  Now can you please add me back as a "collaborator" under settings?
I need to push updates to urls etc. and I'm getting a permission denied error.
Apparently collaborators get lost in this process.
Please also add @johnnychen94 because I won't be able to do that myself now.
Only JuliaIO group members can do that AFAIK.

**Comment by IanButterworth** [comment]
Huh.. didn't expect that. You're now invited back

**Comment by JeffFessler** [comment]
> didn't expect that.

Me neither!  All set now, thanks much, and apologies to everyone else for the multiple notifications...
