### ISSUE TITLE
[FR] suppert for .webp format

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaIO/FileIO.jl#379]
Google's `webp` format is making grand promises: 
> WebP is a raster graphics file format developed by Google intended as a replacement for JPEG, PNG, and GIF file formats. It supports both lossy and lossless compression,[8] as well as animation and alpha transparency. 

I was unable to find a julia package for saving/loading webp files. Could we support that here?

**Comment by stemann** [comment]
https://github.com/stemann/WebP.jl

ImageIO PRs is queued: https://github.com/JuliaIO/ImageIO.jl/pull/67

**Comment by KronosTheLate** [comment]
Amazing!! Thank you, that is really nice :D
