### ISSUE TITLE
Request: Committer access to JuliaIO

### ISSUE THREAD

**Issue by Drvi** [JuliaIO/FileIO.jl#405]
I'm not sure where to ask for this, and since we have PR that we care about this repo (#403), I'll ask here- could our team please get committer access to the JuliaIO org? We've contributed here before, e.g. to `ProtoBuf.jl` and `TranscodingStreams.jl`. GitHub handles of our team: [Drvi](https://github.com/Drvi), [kpamnany](https://github.com/kpamnany), [nhdaly](https://github.com/nhdaly), [d-netto](https://github.com/d-netto), [nickrobinson251](https://github.com/nickrobinson251)
Thank you!

CC: @ViralBShah

**Comment by ViralBShah** [comment]
Done. @kpamnany is already a member and should have access.
