### ISSUE TITLE
What to put in Require

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/FileIO.jl#42]
As discussed in https://github.com/timholy/Images.jl/commit/2762928da596360fb84c0248bff8e387cdced2c2#commitcomment-13530108 and https://github.com/timholy/Images.jl/pull/374/files#r40807839 

Solutions:
- put Important packages in the Require
- list of recommended packages
- when it's detected that a package could load a file, but it's not installed, prompt the user to install it (maybe even offering to install it automatically)

I'm in favor of the last option, since it deals with the problem of only installing the minimal set of needed packages while still keeping usability up high.

I can prepare a PR when you all agree!

Best,
Simon

**Comment by SimonDanisch** [comment]
The more I try to fix errors in the ImageMagick and QuartzImageIO builds, the more I'm convinced that option 3 is the way to go. Putting anything in any REQUIRE seems to lead to hassle, if someone prefers another package than in the REQUIRE.

**Comment by timholy** [comment]
Prompting seems reasonable to me; I was beginning to come to the same conclusion.

**Comment by rsrock** [comment]
I agree, this should be under the user's control

**Comment by timholy** [comment]
Fixed
