### ISSUE TITLE
Bad interaction with MIME display

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/FileIO.jl#44]
In the Jupyter notebook, a cell with 
```
foo = "bar"
``` 

is fine, but 

```
using FileIO
foo = "bar"
```

gives

```
MethodError: `start` has no method matching start(::Symbol)

 in writemime at /Users/rrock/.julia/v0.4/FileIO/src/FileIO.jl:105
 in base64encode at base64.jl:160
 in display_dict at /Users/rrock/.julia/v0.4/IJulia/src/execute_request.jl:32
```

I first saw this here at the REPL, because my startup file includes TerminalExtensions.jl:

```julia
❯ julia --startup-file=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc3 (2015-09-27 20:34 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin15.0.0

julia> using FileIO

julia> foo = "bar"
"bar"

julia> using TerminalExtensions

julia> foo = "bar"
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
WARNING: Base.Base64Pipe is deprecated, use Base.Base64.Base64EncodePipe instead.
1mERROR: MethodError: `start` has no method matching start(::Symbol)
 in writemime at /Users/rrock/.julia/v0.4/FileIO/src/FileIO.jl:105
 in display at /Users/rrock/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:169
 in display at /Users/rrock/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:179
 in display at multimedia.jl:151
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:625
 in anonymous at /Users/rrock/.julia/v0.4/TerminalExtensions/src/TerminalExtensions.jl:227
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:864
 in run_repl at ./REPL.jl:168
 in _start at ./client.jl:453
```

**Comment by timholy** [comment]
I don't have a working Jupyter or IJulia, so it's not easy to test. What is line 105? (i.e., which `sha` are you on?) What are the contents of `mime`, `x`, and `handlers`?

**Comment by SimonDanisch** [comment]
I think I'm on the right track to solve these issues... I'll report back when I fixed it.

**Comment by SimonDanisch** [comment]
Okay... We did everything wrong for `writemime` :D I have the feeling we can't handle `writemime` in FileIO, since the whole thing builds upon the assumption, that no one overloads `writemime` with the last type being `Any`.  It works now, but I'm stuck with the images being stretched (after they looked okay with my first fix, which wasn't a complete fix).
I'm investigating this further...

**Comment by SimonDanisch** [comment]
>    We did everything wrong for writemime
By everything wrong I mean, that mimewritable is defined in Base as `mimewritable(mime, x) = methodexists(writemime, Tuple{IO,typeof(mime), typeof(x) )`, which made everything `mimewritable` because of the definition in FileIO.

**Comment by timholy** [comment]
Oh, wow, that is problematic.

Probably best to just have the individual loaders/savers implement it, without a dispatcher in FileIO.

**Comment by SimonDanisch** [comment]
Yeah exactly... That's what I'm going for right now...
I just don't know why the images started looking terrible.
![image](https://cloud.githubusercontent.com/assets/1010467/10268566/2576d7d2-6abd-11e5-89a8-e85cbff0c8c9.png)
This is what I get... Any ideas? I was thinking it's because the key_args get ignored, or so... But that's not the case. Is this a problem in IJulia?! I think I updated IJulia between my fixes, which could explain the change.

**Comment by timholy** [comment]
Using Images v0.4.50 it looks fine to me. (That doesn't use the ImageMagick package, so you could test whether it's your IJulia or the package.)

**Comment by SimonDanisch** [comment]
Thanks! I'll check it out

**Comment by SimonDanisch** [comment]
Okay, I don't really know what I did, but it seemed like I changed something in Images while debugging which did this... Looks fine now, after resetting Images to master.

**Comment by timholy** [comment]
Great to hear!

**Comment by rsrock** [comment]
Is this now fixed and we can close this?

**Comment by SimonDanisch** [comment]
It's not merge yet, so not officially fixed ;)

**Comment by rsrock** [comment]
Ah, I I see now, this is in your error branch.  I think this is uncoupled from the rest of the error handling?  If so, it can go in on it's own.

**Comment by SimonDanisch** [comment]
Yeah, I regretted it the minute I pushed it into that branch... Hopefully it's ready for a merge, so I can just squash it.
