### ISSUE TITLE
`RIFF` header used for `.avi` and `.wav` files

### ISSUE THREAD

**Issue by ssfrr** [JuliaIO/FileIO.jl#47]
Both `.avi` and `.wav` files use `RIFF` as their magic bytes, followed by 4 bytes of size information and then `WAVE` or `AVI`.

What's the general strategy for nested file types like this? Should there be a `format"RIFF"` loader that then dispatches to separate `format"WAV"` and `format"AVI"` loaders? Another option would be to fall back to file type if the magic bytes conflict, but that doesn't help you e.g. if you have a generic container type that can have different contained file types.

**Comment by SimonDanisch** [comment]
This could be solved with a detection function?

>Should there be a format"RIFF" loader that then dispatches to separate format"WAV" and format"AVI" loaders?

I like that idea as well. It could also be used to solve #32
