### ISSUE TITLE
Read and write or load and save?

### ISSUE THREAD

**Issue by mbauman** [JuliaIO/FileIO.jl#5]
I first thought about creating this sort of package because of the save method collisions in DataFrames and HDF5 (https://github.com/timholy/HDF5.jl/pull/101).  The words `load` and `save` have a higher-level connotation to me than read/write, and packages seem to be already using that sort of terminology.  I'm not sure if there's a particularly compelling reason to use one or the other, but I wanted to open the discussion.

**Comment by SimonDanisch** [comment]
I actually just wanted to open an issue about that. I guess I was biased by imread, imwrite... I don't have strong feelings about the names. Load and save seem equally eligable.

**Comment by mbauman** [comment]
Have you been running into any ambiguities in defining `read(::FileType, …)`?  I think most methods are pretty clearly written `read(::IO, …)`, but it's such a common function there may be other forms.

**Comment by SimonDanisch** [comment]
Ambiguities are definitely a problem. In #3 i propose using some kind of normal form to solve this.
I kind of ignores io so far :-D maybe it's time to change that and think about where and how to introduce it...

**Comment by SimonDanisch** [comment]
I actually don't describe the normal form in this issue :D 
I'll create a schematic if I find some time, to explain things a bit better!
Best,
Simon

**Comment by timholy** [comment]
We've gone with `load` and `save`.
