### ISSUE TITLE
Fallback to display for known MIME types?

### ISSUE THREAD

**Issue by mbauman** [JuliaIO/FileIO.jl#6]
For saving some file formats like HTML, markdown, and images, it may make sense to fallback to the display hierarchy with MIME types for writing.  This would, for example, allow one to save any plot with a simple `write(File("plot.png"), plt)` without any new code on the part of the plotting package.  It'd be essential to pass through keyword arguments to allow optional formatting specifications (but that's another can of worms).

This would also mean that string IO would simply fall back to `print` with any `.txt` file.

**Comment by SimonDanisch** [comment]
Hm seems like a good idea... I haven't fully embraced MIMEs yet, as they were too coarse for my use cases so far... But something like this seems very elegant!

**Comment by timholy** [comment]
I think this is done by `FileIO.MimeWriter`
