### ISSUE TITLE
Integrate ExcelReaders

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/FileIO.jl#7]
I'd be happy to integrate [ExcelReaders](https://github.com/davidanthoff/ExcelReaders.jl) into this framework at some point. You might take a quick look at it to get a sense whether the APIs will match or not.

**Comment by SimonDanisch** [comment]
That's exciting!
Well, all you need is some package that defines the object that you will return upon reading the file.
This package should load the correct IO functions from your `ExcelReaders` package on demand.
I guess that my examples are not too clear, but I hope that I find some time to draw a schematic to better explain the planned infrastructure.

Best,
Simon

**Comment by timholy** [comment]
ExcelReaders looks like a useful package. 

I think you can do this now, see the README. When you want a `DataFrame` output, you should be able to implement this as `load(filename, DataFrame, "Sheet1!A1:C4", header=false)`.

**Comment by davidanthoff** [comment]
Right now I have ``readxl`` (where you specify an exact Excel range to read) and ``readxlsheet`` (where the package finds the data on an Excel sheet). I had considered combining them into one function, but at the end it just seemed easier to have two functions because they actually do quite different things. I'm not sure how that would map onto the ``load`` function from this package... Maybe just have the ``load`` function use ``readxl`` and not expose the ``readxlsheet`` function via ``FileIO``?

**Comment by timholy** [comment]
You have several options, including keywords or parsing the string to look for `!`. Or if you prefer dispatch, you could define
```jl
immutable XslRange
    start::Symbol
    stop::Symbol
end
```
and then `load("filename.xslx", "Sheet1", XslRange(:A4,:C4))`. Write a separate version of the `load` function for `XslRange` inputs.

**Comment by davidanthoff** [comment]
I had considered all of these, and for various reasons none of them is ideal (parsing for ``!`` is bad because the set of optional keyword parameters to the method is different depending on whether someone is reading a whole sheet or a range, ``XslRange`` is tricky because I hope to extend the range syntax to accept more flexible forms in the future, and using an immutable with fixed fields would make that difficult, plus it just seems more complicated for users to remember/learn).

I guess one pretty basic question is what would a user gain if ExcelReaders was integrated with FileIO? One would still need to know the non-standard load method signature for specific Excel files, right? I fully understand that it is nice to be able to call ``load(filename)`` and get a return value of the appropriate type, but that would never work for Excel files in any case.

**Comment by SimonDanisch** [comment]
I think the advantages of FileIO are two fold.
First, it gives you the same interface for loading a file. But I also have the hope, that it will help to get more homogeneous IO packages in general.
It will help to spread ideas and programming patterns that are helpful for elegant IO and might help to offer a consistent feature set across the different packages.
That's probably not as important if you wrap an existing IO library.

For your current problem I would recommend this pattern:
```Julia
load(file::format"XSLX"; name="Sheet1", range=findrange(file), more_flexible_future_proof_stuff=...) = ...
```
> plus it just seems more complicated for users to remember/learn

I agree that additional types could be a little harder, but I think keyword arguments should not be that much more difficult to learn.
It seems we don't have that option yet, but as soon as we can query the keywords for a certain method, this will even be easier.

Some other patterns I learned to like:
```Julia
Base.call(::Type{ExcelSheet}, ::format"XSLX") = #helpful if you have multiple types, guarantees to get the queried type
Base.call(::Type{DataFrame}, ::format"XSLX") =
Base.call(a::Array, f::format"XSLX") = load!(a, f) # only loads size(a)
```

>I fully understand that it is nice to be able to call load(filename) and get a return value of the appropriate type, but that would never work for Excel files in any case.

You said that `readxlsheet` offers this, so it should be possible to have some default that probably doesn't satisfy advanced demands, but gives the new user an easy start ;)

**Comment by timholy** [comment]
It may not apply to your case, but for me one big advantage is that FileIO provides a mechanism to support IO without package interdependencies.

Let's say someone makes a spreadsheet analysis program. They may be grumpy about depending on all those packages (`ExcelSheet`, `OpenDocumentSheet`, `GnumericSheet`, `CSVReaders`, `LotusSheet`, `dBaseSheet`, `FileMakerSheet`, etc), because it will increase their package load time. Instead, they can depend on just `FileIO` and dispatch to the right function based on the output of `query`.

Of course, that's an argument against my `XslRange` type above. Better to use "generic" objects.

**Comment by timholy** [comment]
If this moves forward, it will be via pull request, so I'm closing this.

**Comment by davidanthoff** [comment]
Actually, here is another idea how to integrate this: I could just define a ``FileIO.load`` that returns an object of type ``ExcelReaders.ExcelFile``. It would just be a 100% the same thing as the existing ``ExcelReaders.openxl`` function.

One would then need to use functions like ``ExcelReaders.readxl`` and ``ExcelReaders.readxlsheet`` to access specific parts of the Excel file by passing that ExcelFile object instead of a filename.

I see two benefits:
1) This would be analogous to reading e.g. an image file, the ``FileIO.load`` function in those cases also just returns a special type that holds the image, and then you need to use image specific functions to access the content
2) The ``FileIO.load`` function would just work with Excel Files, no need to know about extra arguments etc.

Does that make sense?

**Comment by davidanthoff** [comment]
Also, before just closing an issue, I would suggest to ask the original creator of the issue to close the issue to make sure things are actually resolved.
