### ISSUE TITLE
read RGB tif image is not correct for the first page

### ISSUE THREAD

**Issue by jingpengw** [JuliaIO/FileIO.jl#70]
I read some tif files, but there result has some artifacts.

notice the grid like things are artifacts. the values were changed after reading. The wired part is that only part of them are incorrect! And for multi-page tif, only the first page has this artifact.
![image](https://cloud.githubusercontent.com/assets/7651573/16741981/c6eb16f8-4773-11e6-9b4e-e2e488c407d3.png)

code:

```
using FileIO
using ImageView
image = load("test.tif")
view(image)
```

with this simple code, you have to zoom in the error part and look at it carefully.

test data:

[test.tif.zip](https://github.com/JuliaIO/FileIO.jl/files/357782/test.tif.zip)

my versioninfo:

ubuntu 14.04

```
versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

ImageMagick.libversion
v"6.7.7"

**Comment by timholy** [comment]
This seems likely to be a bug in the ImageMagick C library---there's no julia code that I can think of that would account for corrupting specific pixel values.

**Comment by timholy** [comment]
I just tested and don't see the "textured" surfaces. However, all the hues are blue for me. Is it supposed to be that way?
![image](https://cloud.githubusercontent.com/assets/1525481/19014820/f52cac8c-87bc-11e6-9889-bbbfc01fb49c.png)

Curiously, I'm on the same platform with the same lib version:
```jl
julia> ImageMagick.libversion
v"6.7.7"
```

**Comment by timholy** [comment]
It seems all blue by every application I've tried. Closing
