### ISSUE TITLE
Memory overflow when using FileIO

### ISSUE THREAD

**Issue by mfalt** [JuliaIO/FileIO.jl#73]
I previously posted this on `Images.jl` but i was able to narrow it down to `FileIO.jl`. I am having trouble to find the source of this bug since my computer hangs when running this, but I have been able to narrow it down to this package, so any help on what logs I can submit here would be helpful.

When I run the following on Julia Version 0.5.0-rc1+0
```
julia> using FileIO
```
I get almost 100% (of 32GB) memory usage and then my computer basically freezes as it starts eating up swap. I am able to `pkill` julia, but I'm not sure on where I can find an appropriate log. I'm on the latest tagged version of FileIO.jl (0.1.0). I tried to do a `Pkg.rm("FileIO"); Pkg.add("FileIO")` but it didn't help. I don't seem to have problems with other packages.

I'm running Fedora 23.

**Comment by timholy** [comment]
This is a julia bug, but fortunately already fixed: update to at least `rc1+1`.
