### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ssfrr** [JuliaIO/FileIO.jl#74]
I'm trying to go through and tag some packages I've been working on and I'm currently depending on FileIO master to get #69. If there's nothing specific holding up a release it would improve my life if you could tag a new version with that fix. :) Thanks!

**Comment by timholy** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6085

**Comment by ssfrr** [comment]
you're my hero.
