### ISSUE TITLE
Cross check with CSVReaders API

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/FileIO.jl#8]
Might be worth taking a look at [CSVReaders](https://github.com/johnmyleswhite/CSVReaders.jl) API to see whether there is some inspiration there.

**Comment by timholy** [comment]
That looks mostly orthogonal to this. The strategy would be to register the `CSVReaders` as a loader/saver (see the README). For incremental reading, `io = open(query(filename))` would give you the `io` object you need. See #18.

**Comment by timholy** [comment]
In the absence of specific suggestions, I'm closing, but feel free to reopen.
