### ISSUE TITLE
Extending FileIO documentation

### ISSUE THREAD

**Issue by prcastro** [JuliaIO/FileIO.jl#9]
We need to document how to extend FileIO to new filetypes.

**Comment by SimonDanisch** [comment]
Definitely! I'm slowly fighting my way forward beside working on my thesis....
Right now I integrate FileIO into GLAbstraction, which will act as a first test of my concepts.
Also it will help finding some bugs... After that I wanted to write something down. 
I figured, I shouldn't try to convince people to integrate this, before I can't be sure that things work relatively well.
If someone is motivated to just help building this up, things look definitely different =)

**Comment by timholy** [comment]
Closed by #15
