### ISSUE TITLE
The magic number for PCX files is too strict

### ISSUE THREAD

**Issue by magister-ludi** [JuliaIO/FileIO.jl#90]
The magic number for PCX format is set as `UInt8[0x0a,0x05,0x01,0x01]` in [registry.jl](https://github.com/JuliaIO/FileIO.jl/blob/master/src/registry.jl). The fourth element represents the number of bits per pixel, so that `load(filename)` can fail for images that will correctly load with `load(File(format"PCX", filename))`.
The [attached](https://github.com/JuliaIO/FileIO.jl/files/671615/testpcx.zip) 256-colour PCX file (zipped, so that it can be attached), with `0x08` as the fourth byte, is a simple example.

**Comment by timholy** [comment]
Looks like really only the first byte is technically the magic byte; the others encode information that might be useful to a parser.

**Comment by magister-ludi** [comment]
Strictly speaking, that's true. The third byte (encoding) should always be `0x01`. The second byte (version) is almost always `0x05`. In my own software, I have used the first three bytes for many years without a problem. However I don't know whether older PCX files (versions `0x00`, `0x02`, `0x03`, `0x04`) are still out there. or how much software actually supports earlier versions.
I think your options are
1. Use only the first byte, though I can understand any reluctance to do that.
1. Use the first three bytes, noting that images before version 3.0 (`byte3==0x05`) don't support magic number recognition
1. Remove the magic number for PCX format. In a practical sense, this is the situation that exists now, as the magic number is unreliable. Removal would make that explicit.
While option 2 would be the convenient for me, there are disadvantages with each of the options. It's really your call on which to choose, although I think the zeroth option (doing nothing) is not the best one.

**Comment by timholy** [comment]
We also have a function version that is more flexible...see the code for HDF5.

**Comment by timholy** [comment]
Though I'd be perfectly happy with option 2

**Comment by magister-ludi** [comment]
Thanks for the tip about HDF5. For now it might be more overhead than I want, but I will keep it in mind. In the meantime, I've built a workaround into my own code.

I'm happy to close the issue now, and leave to you whether to make relevant changes to the FileIO code.

**Comment by timholy** [comment]
If you're willing to tackle the fix, that would be a huge help. If not, let's at least leave this open until some motivated individual steps forward.

**Comment by magister-ludi** [comment]
Happy to do that. I'll report when it's ready.

**Comment by timholy** [comment]
Awesome. To clarify, I didn't mean "store your data in HDF5 format" (though of course that's OK too), but simply that if you need to implement complicated logic to recognize the magic bytes, you can look at [how we recognize HDF5 files](https://github.com/JuliaIO/FileIO.jl/blob/fa4d8740bf954d662b81ccf8fb246695a55e9299/src/registry.jl#L143-L165) as a model. However, if you want to implement an easier option, that's fine too.

**Comment by magister-ludi** [comment]
Thanks for the clarification. I think setting things up for version 3.0 (i.e. modern) PCX should be straightforward, but I'll try to make it work for earlier versions too (assuming they still might exist).

**Comment by timholy** [comment]
Closed by #114
